Gemfile.lock, app/controllers/users_controller.rb, config/routes.rb, test/controllers/users_controller_test.rb
=> add user controller

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss
=> add colors and fonts

app/models/user.rb, db/migrate/20220830142201_add_name_to_users.rb, db/migrate/20220830142406_add_bio_to_users.rb, db/migrate/20220830142447_add_problem_to_users.rb, db/migrate/20220830142705_add_displaced_to_users.rb, db/schema.rb
added bio, name, problem and displaced (boolean) to the User model
=> Rails migrations

app/controllers/reviews_controller.rb, app/models/review.rb, app/models/user.rb, app/views/reviews/new.html.erb, config/routes.rb, db/migrate/20220830141359_create_reviews.rb, db/schema.rb, test/controllers/reviews_controller_test.rb, test/models/review_test.rb
reviews cotroller needs show template
=> reviews cotroller needs show template

app/controllers/buddies_controller.rb, app/controllers/reviews_controller.rb, app/models/buddy.rb, app/models/chat.rb, app/models/message.rb, app/models/review.rb, app/models/user.rb, app/policies/buddy_policy.rb, app/policies/review_policy.rb, app/views/buddies/new.html.erb, app/views/buddies/show.html.erb, app/views/reviews/new.html.erb, config/routes.rb, db/migrate/20220901114612_add_status_to_buddies.rb, db/migrate/20220901134803_add_buddies_reference_to_message.rb, db/migrate/20220901142310_drop_chats.rb, db/migrate/20220901144200_change_foreign_key_for_message.rb, db/schema.rb, test/controllers/biddies_controller_test.rb, test/controllers/boddies_controller_test.rb, test/controllers/buddies_controller_test.rb, test/policies/buddy_policy_test.rb
MIGRATION CHANGE, REVIEW AND BUDDY CONTROLLERS
=> MIGRATION CHANGE, REVIEW AND BUDDY CONTROLLERS

app/controllers/messages_controller.rb, config/routes.rb, db/schema.rb
=> messages controller almost done should be added path and buddies id

db/seeds.rb
probably still missing the user_tag seeds so that there is a connection btw users and tags
=> added tags seeds

app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/controllers/profiles_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/logo_rotate_controller.js, app/views/pages/home.html.erb, app/views/profiles/index.html.erb, app/views/shared/_navbar.html.erb
finish landingPage logo error and logo with rotate
=> finish landingPage with rotate

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_profiles.scss, app/assets/stylesheets/config/_fonts.scss, app/views/profiles/index.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_tabbar.html.erb, db/schema.rb
check this shit outttt 🔥💩 it's on fire
=> fixed backside of cardand other bugs

app/assets/stylesheets/components/_profiles.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/profiles/index.html.erb, app/views/profiles/show.html.erb
=> added show page-missing reviews

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_profiles.scss, app/assets/stylesheets/components/_tabbar.scss, app/controllers/profiles_controller.rb, app/models/tag.rb, app/views/profiles/index.html.erb, db/migrate/20220907101040_create_pg_search_documents.rb, db/schema.rb
=> finish search tags

app/controllers/buddies_controller.rb, app/controllers/profiles_controller.rb, app/views/buddies/index.html.erb, app/views/buddies/show.html.erb
=> add buddies

app/views/profiles/index.html.erb
=> finish buddy path

app/controllers/profiles_controller.rb, app/controllers/reviews_controller.rb, app/views/buddies/index.html.erb, app/views/reviews/new.html.erb
Was added button "Review" to buddy profile only when you are friends
=> add button review to buddy profile

app/assets/stylesheets/components/_tabbar.scss, app/views/buddies/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_tabbar.html.erb
=> fitxed footer position

app/controllers/locations_controller.rb, app/views/locations/index.html.erb
check search by category on location
=> search by category on the map

app/controllers/reviews_controller.rb, app/models/buddy.rb, app/models/user.rb, app/views/buddies/index.html.erb
Add review view to buddies profile
=> add review view to buddies profile

app/assets/stylesheets/components/_profiles.scss, app/views/buddies/index.html.erb, app/views/profiles/index.html.erb
=> bio show padding 20px

app/views/shared/_chatbar.html.erb
=> buttons on avatar and link to profile show

app/controllers/pages_controller.rb, app/views/chats/index.html.erb, app/views/shared/_navbar.html.erb
=> fixed ugly button from chat. well done

db/seeds.rb
=> remove refugee

app/assets/stylesheets/components/_profiles.scss, app/views/buddies/index.html.erb, app/views/profiles/index.html.erb, app/views/profiles/show.html.erb
gotta check card flip in buddies
=> added review if else
